apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: client
          servicePort: 80
      - path: /api/add/*
        backend:
          serviceName: add
          servicePort: 8080
      - path: /api/sub/*
        backend:
          serviceName: sub
          servicePort: 8081
